language: php

php:
  - 5.4
  - 5.5

before_script:
    - composer self-update
    - composer install -n --prefer-source
    - export ADDITIONAL_PATH=`php -i | grep -F --color=never 'Scan this dir for additional .ini files'`
    - echo 'xdebug.max_nesting_level=9999' | sudo tee ${ADDITIONAL_PATH:42}/symfony2.ini

script: phpunit -c app
