 # This file is part of Redado.
 #
 # Copyright (C) 2013 Guillaume Royer
 #
 # Redado is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # Redado is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Affero General Public License for more details.
 #
 # You should have received a copy of the GNU Affero General Public License
 # along with Redado.  If not, see <http://www.gnu.org/licenses/>.

Redado\CoreBundle\Entity\Group:
    type: entity
    repositoryClass: Redado\CoreBundle\Entity\GroupRepository
    table: groups
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        sysname:
            type: string
            unique: true
            length: 255
        name:
            type: string
            length: 255
        description:
            type: text
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        modified:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        memberships:
            targetEntity: Membership
            mappedBy: group
            cascade: [persist, remove]
            orphanRemoval: true
        closuresParents:
            targetEntity: GroupClosure
            mappedBy: child
            cascade: [persist, remove]
            orphanRemoval: true
        closuresChildren:
            targetEntity: GroupClosure
            mappedBy: parent
            cascade: [persist, remove]
            orphanRemoval: true
        permissions:
            targetEntity: Permission
            mappedBy: object
            cascade: [persist, remove]
            orphanRemoval: true

    lifecycleCallbacks: {  }
